def kmers(text, k):
    return [text[i:i+k] for i in range(len(text)-k)]


def count_kmers(kmers):
    output = {}
    for i in kmers:
        if i not in output:
            output[i] = 0
        output[i] += 1
    return output


def get_most_common_kmers(kmer_count: dict):
    return [i for i, j in kmer_count.items() if j == max(kmer_count.values())]


if __name__ == '__main__':
    # test case
    text = "ACGTTGCATGTCGCATGATGCATGAGAGCT"
    k = 4
    kmers_lst = kmers(text, k)
    kmer_count = count_kmers(kmers_lst)
    print(' '.join(get_most_common_kmers(kmer_count)))

    # user case example
    text = "GTATTAGCTTGCCGTAATGAGTAAATCAGTAAATCAGCCGTAATGAGTATTAGCTTATGGATATACCGTAGCGTAAATCAATGGATATATGGATATGTAAATCAGCCGTAATGAATGGATATGTAAATCAGTATTAGCTTGCCGTAATGAATGGATATGTATTAGCTTGTAAATCAGCCGTAATGAACCGTAGCGTAAATCAATGGATATGCCGTAATGAGTATTAGCTTATGGATATGTATTAGCTTGTAAATCAATGGATATGTAAATCAGTAAATCAATGGATATGCCGTAATGAACCGTAGCGTATTAGCTTATGGATATGTAAATCAACCGTAGCATGGATATATGGATATGTAAATCAATGGATATGTATTAGCTTGCCGTAATGAGCCGTAATGAGTATTAGCTTGCCGTAATGAGCCGTAATGAACCGTAGCGCCGTAATGAATGGATATGCCGTAATGAATGGATATACCGTAGCGTATTAGCTTGCCGTAATGAACCGTAGCACCGTAGCGTAAATCAACCGTAGCACCGTAGCGTATTAGCTTGTATTAGCTTGTATTAGCTTGTATTAGCTTATGGATATGTATTAGCTTGCCGTAATGAGTATTAGCTTGCCGTAATGAACCGTAGCGTATTAGCTTACCGTAGCGCCGTAATGAGTAAATCAGCCGTAATGAACCGTAGCGCCGTAATGAGTAAATCAATGGATATGTAAATCAATGGATATATGGATATGTAAATCAACCGTAGCACCGTAGCATGGATATGCCGTAATGAGTATTAGCTTGTATTAGCTTGTAAATCAGCCGTAATGAGTAAATCAGTAAATCAACCGTAGCGTATTAGCTTGTATTAGCTTATGGATATGTAAATCAGTAAATCAACCGTAGCACCGTAGCATGGATATGTAAATCAGCCGTAATGAACCGTAGCACCGTAGCGCCGTAATGAGCCGTAATGAGCCGTAATGAATGGATAT"
    k = 11
    kmers_lst = kmers(text, k)
    kmer_count = count_kmers(kmers_lst)
    print(' '.join(get_most_common_kmers(kmer_count)))
