from itertools import product
import re


def get_all_kmers(alphabet, k):
    return (''.join(i) for i in list(product(alphabet, repeat=k)))


def get_frequency_array_of_string(text, k):
    all_kmers = list(get_all_kmers(["A", "C", "G", "T"], k))
    output = (len(re.findall('(?={0})'.format(re.escape(i)), text)) for i in all_kmers)
    return output


if __name__ == '__main__':
    # test case
    text = "ACGCGGCTCTGAAA"
    k = 2
    freq_array = get_frequency_array_of_string(text, k)
    print(' '.join([str(i) for i in freq_array]))

    # user case example
    text = "TCCATTGAGTTCTTCGCCTCCAAGCCTAAATCTATTCGAACTGGGTAACTTTGAGTTGCCAAGCCTATTCCTCCGTGATATTATGACGTCCGTATTTGTTGTGAGCTTCTGCATCCCGGTTATCAAGAATAAGTAGAGTGCATTACGGTTCTAAAGAGGCGTCCATAATGGGTGATCGTCGGTCTAAACGTAAGAAAGTGCTGTAGAACGCACATTCTTGAATTCCCCCCGGCCTGCAATTAAATTGGATCGTAAAGATCTTTAATATCAGTAGAAGTGTGTATTGTTTGAGGTCGTCGAGGAGTCCGCTAGTAGAGCTTCGCATGTGTCCCCGGACTGAGGCCAACTCTTTAAACCTCAGGGGGGATATTCGGTGAAAGACTATAAGATTTCCGGCCCCAAATCACTTCTGCCGTGGTACAAATTGAATTTGTCAATTGCACGTAGAGAAGAAGTGTACCTCTCTCTATCCACATACAAAGGAACGTCTGTAGCGTCATCGGGGCGGATACTACTAGTTCCATTTCACGTGAATTTAGCAGTGACAGCAGATAATGGTCCTGTAATGGTGAGACCAGCGAGGGATGTCCTCTCGGACCACCAAAACTACGTTTACTGGGCTGTGACGTCATTAAGCCGTAAGTGACCTGCCTAATGCCTCTTTGAAGGGCCCTTAATTTATTACGAGGGTTCGTGATGCTAATGGAGGGCATACGTGGTTGTGACTTGGAGTATGCGGCACCGGCGCCGTCGGTTACTCCTAAGT"
    k = 7
    freq_array = get_frequency_array_of_string(text, k)
    print(' '.join([str(i) for i in freq_array]))
